RTreeDisk - disk_backed
bglasber/nir-tree pull request #1
Opened 2021-10-24 12:23 UTC by sergiupocol

src/include/rtreedisk/*  contains the implementation for RTreeDisk and it's corresponding node class.

src/tests/testRTreeDisk.cpp contains the tests the cover the main functions in the Index.h interface along with findLeaf and findLeaf on Disk

2021-10-30 20:08 UTC, sergiupocol commented on src/include/rtreedisk/node.h
> +            allocator->get_tree_node<NodeType>(child)->parent = self_handle_;
Yes, it's usage is strictly in testRTreeDisk and in that context I believe addEntry is only called on the parent.

2021-11-02 03:03 UTC, bglasber requested changes
Just a few final things regarding naming and using std::get<> & references where appropriate.

Just tested with the California dataset (2D, 1.8 million points) and it all loads and validates successfully. Great work! 

I will break off a task from the NIR-Tree allocator optimizations and talk to you mid-week about how we get can started on that.

2021-11-02 03:03 UTC, bglasber commented on src/tests/testRTreeDisk.cpp
> +static NE createBranchEntry(const Rectangle
If you do end up keeping the duplicates and put the _local version here instead, you can try using the following VIM command trick:

:%s/createBranchEntry/createBranchEntry_local/g

2021-11-02 18:34 UTC, sergiupocol commented on src/include/rtreedisk/node.tcc
> +        Branch b = std::get<Branch>( entries.at(i) );
Thanks! I think all instances of Branch b = ... are not modifying b but just reading so all can be converted to references

2021-11-04 00:31 UTC, bglasber approved these changes

2021-11-04 16:31 UTC, merged